# Generated by Django 5.2.6 on 2025-09-26 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ico', models.CharField(blank=True, max_length=20, verbose_name='IČO')),
                ('dic', models.CharField(blank=True, max_length=20, verbose_name='DIČ')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='Česká republika', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Číslo faktury')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('variable_symbol', models.CharField(blank=True, max_length=20, verbose_name='Variabilní symbol')),
                ('status', models.CharField(choices=[('draft', 'Návrh'), ('issued', 'Vystavená'), ('paid', 'Zaplacená'), ('cancelled', 'Stornovaná')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='DPH %')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='Číslo účtu')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Popis')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Množství')),
                ('unit', models.CharField(default='ks', max_length=20, verbose_name='Jednotka')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena/jedn. (bez DPH)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
    ]
